### ISSUE TITLE
Changing the TTS voice

### ISSUE THREAD

**Issue by ripvega** [tetele/onju-voice-satellite#27]
I have 'Ryan Neural' set as my assistant voice but the TTS speech comes out as a female American (not that there's anything wrong with that).

How is the TTS voice set to be the same as the assistant voice?

**Comment by jherby2k** [comment]
Has nothing to do with the onju at all, but i do know the answer. Are you using tts.speak like this?

'''yaml
service: tts.speak
data:
  media_player_entity_id: media_player.bedroom_speaker
  message: "Testing 123"
target:
  entity_id: tts.piper
'''

It'll use the voice configured in the piper add-on settings.
