### ISSUE TITLE
[Feature Request] feedback after setting volume

### ISSUE THREAD

**Issue by jherby2k** [tetele/onju-voice-satellite#28]
If i set the volume in Home Assistant, ideally it would blink the volume indicators on the device. Right now there is no feedback at all.

Also Google has the device "click" as sort of a "volume preview" when you turn it up or down. It should do that when setting the volume, regardless of manner.

**Comment by tetele** [comment]
Due to the mutex limitation in ESPHome, the click might not be possible when listening for wake word.

However, I agree it would be a nice thing to temporarily flash the volume LED configuration even when the volume is changed off-device.
