### ISSUE TITLE
Voice assistant doesn't listen when the media player is paused

### ISSUE THREAD

**Issue by jherby2k** [tetele/onju-voice-satellite#30]
I understand it can't currently play audio and listen at the same time, however - if the media_player is currently paused (rather than idle) it also can't accept any voice commands. Its actually kinda hard to stop playback in HA - i couldn't find a stop button and had to use an API call media_player.media_stop to get it back to "idle" so that it would listen to me again.

not sure how to work around this... maybe turning on "Use Wake Word" should send media_player.media_stop? Then you can fix it by just toggling that.

**Comment by tetele** [comment]
Interesting use case. I'll add just that: stopping the `media_player` when the wake word toggles on.
