### ISSUE TITLE
[Question] The ESPHome in progress binary sensor "assist_in_progress" is deprecated.

### ISSUE THREAD

**Issue by VivantSenior** [tetele/onju-voice-satellite#91]
### Flavor

MicroWakeWord

### Checklist

- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/tetele/onju-voice-satellite/issues?q=is%3Aissue+label%3A%22bug%22+)..
- [X] I am able to consult debug logging for my ESPHome instance.

### Describe the issue

As of Home Assistant 2024.10 I received a warning:

```
The ESPHome in progress binary sensor binary_sensor.office_voice_assistant_assist_in_progress is deprecated.

Migrate your configuration to use the corresponding assist_satellite entity and then click SUBMIT to disable the in progress binary sensor and fix this issue.
```

Is there something I can change in the config to get it fixed?

### Reproduction steps

N/A

**Comment by cowboyrushforth** [comment]
To solve this, just delete the ESPHome device, then wait for it to be re-discovered, then add it again.  This solved it for me, at least.
